//
//  DLLOverride.swift
//  WhiskyKit
//
//  This file is part of Whisky.
//
//  Whisky is free software: you can redistribute it and/or modify it under the terms
//  of the GNU General Public License as published by the Free Software Foundation,
//  either version 3 of the License, or (at your option) any later version.
//
//  Whisky is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//  See the GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along with Whisky.
//  If not, see https://www.gnu.org/licenses/.
//

import Foundation

/// Mode for a DLL override entry.
///
/// Each mode controls how Wine resolves a DLL at load time:
/// - ``builtin``: Use Wine's built-in implementation
/// - ``native``: Use the Windows-native DLL from the prefix
/// - ``nativeThenBuiltin``: Try native first, fall back to built-in
/// - ``builtinThenNative``: Try built-in first, fall back to native
/// - ``disabled``: Disable the DLL entirely
public enum DLLOverrideMode: String, Codable, CaseIterable, Sendable, Equatable, Hashable {
    case builtin = "b"
    case native = "n"
    case nativeThenBuiltin = "n,b"
    case builtinThenNative = "b,n"
    case disabled = ""

    /// A human-readable display name for this mode.
    public var displayName: String {
        switch self {
        case .builtin:
            "Builtin (b)"
        case .native:
            "Native (n)"
        case .nativeThenBuiltin:
            "Native then Builtin (n,b)"
        case .builtinThenNative:
            "Builtin then Native (b,n)"
        case .disabled:
            "Disabled"
        }
    }
}

/// A single DLL override entry specifying a DLL name and its override mode.
///
/// The `dllName` should not include the `.dll` suffix.
///
/// ## Example
///
/// ```swift
/// let entry = DLLOverrideEntry(dllName: "dxgi", mode: .nativeThenBuiltin)
/// ```
public struct DLLOverrideEntry: Codable, Equatable, Sendable, Hashable {
    /// The DLL name without the `.dll` suffix.
    public let dllName: String
    /// The override mode for this DLL.
    public let mode: DLLOverrideMode

    /// Creates a new DLL override entry.
    ///
    /// - Parameters:
    ///   - dllName: The DLL name without `.dll` suffix.
    ///   - mode: The override mode.
    public init(dllName: String, mode: DLLOverrideMode) {
        self.dllName = dllName
        self.mode = mode
    }
}

/// Source of a managed DLL override.
///
/// Managed overrides are read-only in the UI and show their source
/// (e.g., "Set by DXVK" or "Set by Launcher fixes").
public enum DLLOverrideSource: Codable, Equatable, Sendable {
    /// Override generated by the DXVK toggle.
    case dxvk
    /// Override generated by selecting the DXMT graphics backend.
    case dxmt
    /// Override generated by a launcher compatibility preset.
    case launcher(String)
    /// User-defined override at the bottle level.
    case userBottle
    /// User-defined override at the program level.
    case userProgram
}

/// A warning generated when a user override conflicts with a managed DLL override.
public struct DLLOverrideWarning: Sendable {
    /// The DLL name that has a conflict.
    public let dllName: String
    /// The managed source that was overridden.
    public let overriddenSource: DLLOverrideSource
    /// A human-readable warning message.
    public let message: String
}

/// Resolves DLL overrides from multiple sources into a `WINEDLLOVERRIDES` string.
///
/// The resolver composes per-DLL overrides with clear precedence:
/// `programCustom[dll] ?? bottleCustom[dll] ?? managed[dll]`
///
/// ## Example
///
/// ```swift
/// let resolver = DLLOverrideResolver(
///     managed: [(entry: DLLOverrideEntry(dllName: "dxgi", mode: .nativeThenBuiltin), source: .dxvk)],
///     bottleCustom: [],
///     programCustom: [DLLOverrideEntry(dllName: "dxgi", mode: .disabled)]
/// )
/// let result = resolver.resolve()
/// // result.overrides == "dxgi="
/// // result.warnings has one entry (DXVK override)
/// ```
public struct DLLOverrideResolver: Sendable {
    /// Managed overrides from DXVK toggle and launcher presets. Read-only in the UI.
    public var managed: [(entry: DLLOverrideEntry, source: DLLOverrideSource)]
    /// Bottle-level custom overrides defined by the user.
    public var bottleCustom: [DLLOverrideEntry]
    /// Program-level custom overrides defined by the user (highest priority).
    public var programCustom: [DLLOverrideEntry]

    /// Creates a new DLL override resolver.
    ///
    /// - Parameters:
    ///   - managed: Managed overrides with their sources.
    ///   - bottleCustom: Bottle-level user overrides.
    ///   - programCustom: Program-level user overrides.
    public init(
        managed: [(entry: DLLOverrideEntry, source: DLLOverrideSource)],
        bottleCustom: [DLLOverrideEntry],
        programCustom: [DLLOverrideEntry]
    ) {
        self.managed = managed
        self.bottleCustom = bottleCustom
        self.programCustom = programCustom
    }

    /// The standard DXVK DLL override preset.
    ///
    /// Applies `n,b` (native then builtin) to the four core DXVK DLLs, and
    /// turns `d3d12` off when the builtin behind it is D3DMetal's.
    ///
    /// DXVK ships no `d3d12`, so the name falls through to the runtime's
    /// builtin. With the GPTK payload deployed, that builtin is D3DMetal's
    /// forwarder: a DX12 game took its adapter from DXVK's DXGI and handed it to
    /// D3DMetal's `D3D12CreateDevice`, which dereferenced a vtable slot on an
    /// object it had not created and jumped to null. Disabling it keeps the
    /// bottle on one implementation, so such a game falls back to D3D11 instead
    /// of half-landing on the other one. A bottle or program set to D3DMetal
    /// resets this to builtin and gets real DX12.
    ///
    /// Without the payload the builtin is Wine's own vkd3d-based `d3d12`, which
    /// turns the foreign adapter away with an error the game can handle, so the
    /// name is left alone. Disabling it there guarded nothing and broke games
    /// that load it at startup: Unity 6000.3 players delay-load `d3d12.dll`, and
    /// a DLL that cannot load at all raises 0xC06D007E, where a failed device
    /// creation lets them carry on in D3D11.
    ///
    /// - Parameter builtinD3D12IsD3DMetal: Whether the runtime's builtin `d3d12`
    ///   is D3DMetal's, which is the case once the GPTK payload is deployed
    ///   (``GPTKImporter/isDeployed()``).
    public static func dxvkPreset(builtinD3D12IsD3DMetal: Bool) -> [DLLOverrideEntry] {
        [
            DLLOverrideEntry(dllName: "dxgi", mode: .nativeThenBuiltin),
            DLLOverrideEntry(dllName: "d3d9", mode: .nativeThenBuiltin),
            DLLOverrideEntry(dllName: "d3d10core", mode: .nativeThenBuiltin),
            DLLOverrideEntry(dllName: "d3d11", mode: .nativeThenBuiltin)
        ] + d3d12Entries(builtinD3D12IsD3DMetal: builtinD3D12IsD3DMetal)
    }

    /// The DXMT DLL override preset.
    ///
    /// The Direct3D translation trio is `n,b` so the DXMT natives copied into
    /// the prefix win, with Wine's builtins as fallback.
    /// `winemetal` is pinned to builtin: DXMT's bridge DLL relies on Wine's
    /// unixlib binding (`__wine_unix_call`) to reach `winemetal.so`, which only
    /// works for builtin-loaded modules — a native copy in the prefix would
    /// load but be unable to call into Metal.
    ///
    /// DXMT has no `d3d12` either, so it gets the treatment described under
    /// ``dxvkPreset(builtinD3D12IsD3DMetal:)``: off when the builtin behind the
    /// name is D3DMetal's, left alone when it is Wine's own.
    ///
    /// - Parameter builtinD3D12IsD3DMetal: Whether the runtime's builtin `d3d12`
    ///   is D3DMetal's (``GPTKImporter/isDeployed()``).
    public static func dxmtPreset(builtinD3D12IsD3DMetal: Bool) -> [DLLOverrideEntry] {
        [
            DLLOverrideEntry(dllName: "dxgi", mode: .nativeThenBuiltin),
            DLLOverrideEntry(dllName: "d3d10core", mode: .nativeThenBuiltin),
            DLLOverrideEntry(dllName: "d3d11", mode: .nativeThenBuiltin),
            DLLOverrideEntry(dllName: "winemetal", mode: .builtin)
        ] + d3d12Entries(builtinD3D12IsD3DMetal: builtinD3D12IsD3DMetal)
    }

    /// `d3d12` for a translation layer that ships none: disabled when the
    /// builtin it would fall through to is D3DMetal's, and not mentioned at all
    /// when it is Wine's own.
    private static func d3d12Entries(builtinD3D12IsD3DMetal: Bool) -> [DLLOverrideEntry] {
        builtinD3D12IsD3DMetal ? [DLLOverrideEntry(dllName: "d3d12", mode: .disabled)] : []
    }

    /// The DLL overrides a graphics backend contributes at bottle level.
    ///
    /// D3DMetal and WineD3D contribute none: both run on Wine's builtin D3D and
    /// pick between themselves with `WINED3DMETAL`. Resolve `.recommended`
    /// before calling, or a bottle gets credited with the wrong set.
    ///
    /// - Parameters:
    ///   - backend: The resolved backend.
    ///   - builtinD3D12IsD3DMetal: Whether the runtime's builtin `d3d12` is
    ///     D3DMetal's, which decides whether DXVK and DXMT turn it off.
    public static func managedPreset(
        for backend: GraphicsBackend, builtinD3D12IsD3DMetal: Bool
    ) -> [DLLOverrideEntry] {
        switch backend {
        case .dxvk:
            dxvkPreset(builtinD3D12IsD3DMetal: builtinD3D12IsD3DMetal)
        case .dxmt:
            dxmtPreset(builtinD3D12IsD3DMetal: builtinD3D12IsD3DMetal)
        case .d3dMetal, .wined3d, .recommended:
            []
        }
    }

    // swiftlint:disable cyclomatic_complexity

    /// Resolves all override sources into a `WINEDLLOVERRIDES` string and warnings.
    ///
    /// Per-DLL resolution: the most specific source wins per DLL name.
    /// The output string is sorted alphabetically by DLL name for deterministic output.
    ///
    /// - Returns: A tuple of the rendered override string and any conflict warnings.
    public func resolve() -> (overrides: String, warnings: [DLLOverrideWarning]) {
        // Build per-DLL effective mode: managed -> bottleCustom -> programCustom
        var effectiveMode: [String: DLLOverrideMode] = [:]
        var managedSources: [String: DLLOverrideSource] = [:]

        // Layer 1: Managed overrides
        for (entry, source) in managed {
            effectiveMode[entry.dllName] = entry.mode
            managedSources[entry.dllName] = source
        }

        // Layer 2: Bottle custom overrides (wins over managed)
        for entry in bottleCustom {
            effectiveMode[entry.dllName] = entry.mode
        }

        // Layer 3: Program custom overrides (wins over all)
        for entry in programCustom {
            effectiveMode[entry.dllName] = entry.mode
        }

        // Generate warnings for overridden managed DLLs
        var warnings: [DLLOverrideWarning] = []
        for (dllName, source) in managedSources {
            guard let finalMode = effectiveMode[dllName] else { continue }

            // Find the managed mode for this DLL
            let managedMode = managed.first { $0.entry.dllName == dllName }?.entry.mode
            guard let managedMode, finalMode != managedMode else { continue }

            // Check if overridden by bottle or program custom
            let isBottleOverride = bottleCustom.contains { $0.dllName == dllName }
            let isProgramOverride = programCustom.contains { $0.dllName == dllName }

            if isBottleOverride || isProgramOverride {
                let sourceDesc: String
                switch source {
                case .dxvk:
                    sourceDesc = "DXVK"
                case .dxmt:
                    sourceDesc = "DXMT"
                case let .launcher(name):
                    sourceDesc = name
                case .userBottle, .userProgram:
                    continue
                }
                warnings.append(DLLOverrideWarning(
                    dllName: dllName,
                    overriddenSource: source,
                    message: "Override for \(dllName) overrides \(sourceDesc) setting"
                ))
            }
        }

        // Render the WINEDLLOVERRIDES string
        guard !effectiveMode.isEmpty else {
            return (overrides: "", warnings: warnings)
        }

        let overrideString = effectiveMode
            .sorted { $0.key < $1.key }
            .map { "\($0.key)=\($0.value.rawValue)" }
            .joined(separator: ";")

        return (overrides: overrideString, warnings: warnings)
    }

    // swiftlint:enable cyclomatic_complexity
}
